config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :reviews do
    resources :comentarios
  end

  root 'reviews#index'
  devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.email == "admin@admin.com" # you can add any condition
        can :manage, :all
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  has_many :comentarios
  has_attached_file :image, styles: { medium: "300x300#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController

def create
  @review = Review.find(params[:review_id])
  @comentario = @review.comentarios.create(params[:comentario].permit(:nome, :body))
  redirect_to review_path(@review)
end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = current_user.reviews.build
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.build(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:Artista, :Titulo, :Genero, :Resenha, :Nota, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/comentarios/_comentario.html.erb
<div class="comentario">
  <div class = "conteudo_comentario">
    <pre class = "nome_comentario"><strong><%= "Autor: "%><%= comentario.nome %></strong>
    </p><%= comentario.body %></p>
    </pre>
  </div>
</div>

app/views/comentarios/_form.html.erb
<%= form_for([@review, @review.comentarios.build]) do |form| %>

<div class="field">
  <%= form.label :nome %><br>
  <%= form.text_field :nome%>
</div>

  <div class="field">
    <%= form.label :comentario%><br>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #00334d opacity:.6; ;" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Do Contra", root_path, class: "navbar-brand" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Novo Review", new_review_path, class: "active" %></li>
          <li><%= link_to "Minha Conta", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

        <% else %>
          <li><%= link_to "Cadastre-se", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Login", new_user_session_path, class: "active" %></li>

        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  <b><i> <cou> Desfile todo o seu ódio (ou amor) aqui </b></i> </cou>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Do Contra</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
    <% content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
  

    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: review, local: true, html: { multipart: true } do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Artista %>
    <%= form.text_field :Artista, id: :review_Artista %>
  </div>

  <div class="field">
    <%= form.label :Titulo %>
    <%= form.text_field :Titulo, id: :review_Titulo %>
  </div>

  <div class="field">
    <%= form.label :Genero %>
    <%= form.text_field :Genero, id: :review_Genero %>
  </div>


    <div class="field">
      <%= form.label :Resenha %>
      <%= form.text_area :Resenha, size: "60x12", id: :review_Resenha %>
    </div>

  <div class="field">
    <%= form.label :Nota %>
    <%= form.number_field :Nota, in: 0.0..10.0, step: 0.5 %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :review_Image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editando Resenha</h1>

<%= render 'form', review: @review %>

<col> <%= link_to 'Mostrar', @review %> | </col>
<col> <%= link_to 'Voltar', reviews_path %> </col>

app/views/reviews/index.html.erb
<div class="linha">
	<% @reviews.each do|review| %>
		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= link_to (image_tag review.image.url(:medium), class: 'image'), review %>
			</div>
		</div>
	<% end %>
</div>
<% if current_user.try(:admin?) %>


<% end %>

app/views/reviews/new.html.erb
<h1> <cou2> Nova Resenha </cou2> </h1>

<%= render 'form', review: @review %>

<cou2> <%= link_to 'Voltar', reviews_path %> </cou2>

app/views/reviews/show.html.erb
<%= image_tag @review.image.url(:medium) %>
<p>
  <li>Artista:</li>
  <p><t></t><p><%= @review.Artista %></p>
</p>

<t>
  <li>Titulo:</li>
  <p><t></t><p><%= @review.Titulo %></p>
</t>

<t>
  <li>Genero:</li>
  <p><t></t><p><%= @review.Genero %> </p>
</t>

<p>
  <strong>Resenha:</strong>
  <ol><%= @review.Resenha %></ol>
</p>

<p>
  <strong>Nota:</strong>
  <li><%= @review.Nota %></li>
</p>

<cou> <%= link_to 'Voltar', reviews_path %> | </cou>

<div id="comentarios">
  <h1><%= @review.comentarios.count %> Comentarios </h1>
  <%= render @review.comentarios %>
  <h2>Fazer um comentario</h2>
  <%= render "comentarios/form" %>
</div>